### ISSUE TITLE
lag_in_frames will not accept 128

### ISSUE THREAD

**Issue by clidx** [BlueSwordM/aom-av1-psy#4]
```
Failed to initialize encoder: Invalid parameter
g_lag_in_frames out of range [..MAX_LAG_BUFFERS] 
```

I tried the Windows binary then built it in Linux, same problem. It doesn't work with 128 and 127 but it works with 96. Edit: actually it works with 96 in Windows but not Linux. Maybe I built the wrong aomenc..? But it didn't complain about the psy and butteraugli tunes.

I have no idea if I'm looking at the right thing but in lookahead.h, MAX_TOTAL_BUFFERS is hard capped at 48+48?
Also if I'm reading av1_cx_iface.c correctly, the raised limit only applies to 1 pass encoding?

**Comment by BlueSwordM** [comment]
The max I've set is actually 120. 

The main branch is the work that will be put in the official aom-av1 build.

The branches that are being used for encoding by yours truly are full-build-4 and full-build-alpha-3, with the alpha build containing the official changes.

**Comment by clidx** [comment]
That explains all of it. I guess that's that, thanks!
